name: Run Jupyter Notebook

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allow running manually from the Actions tab
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    # Add a timeout to prevent the job from running indefinitely
    timeout-minutes: 60
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install exact packages from the notebook
        pip install jupyter nbconvert
        pip install google-generativeai
        pip install IPython
        pip install pillow
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
        pip install kokoro>=0.9.2 soundfile
        pip install numpy requests
        # Install system dependencies
        sudo apt-get update
        sudo apt-get install -y espeak-ng
        
    - name: Run notebook directly
      run: |
        # Run the notebook directly using nbconvert
        jupyter nbconvert --to notebook --execute --ExecutePreprocessor.timeout=1800 --ExecutePreprocessor.allow_errors=True notebook.ipynb --output executed_notebook.ipynb
        
    - name: Upload executed notebook as artifact
      uses: actions/upload-artifact@v4
      with:
        name: executed-notebook
        path: executed_notebook.ipynb
