name: Run Jupyter Notebook

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Allow running manually from the Actions tab
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    # Add a timeout to prevent the job from running indefinitely
    timeout-minutes: 60
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert nbformat
        # Install core dependencies needed for notebook execution
        pip install google-generativeai IPython
        pip install pillow numpy
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
        pip install requests
        # Skip the more problematic dependencies (kokoro, soundfile, etc.) as they'll be skipped in CI mode
        
    - name: Run notebook with CI adaptations
      run: |
        # Run our script that modifies and executes the notebook in CI-friendly way
        python run_notebook.py
        
    - name: Upload executed notebook and logs as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: notebook-execution-results
        path: |
          notebook_ci_ready.ipynb
          executed_notebook.ipynb
          notebook_execution_report.json
          *.log
