name: Run Jupyter Notebook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow running manually from the Actions tab
  workflow_dispatch:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install jupyter nbconvert
        # Install required libraries from the notebook
        pip install google-generativeai IPython
        pip install pillow
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client
        pip install kokoro>=0.9.2 soundfile
        # Install espeak-ng for text-to-speech
        sudo apt-get update
        sudo apt-get install -y espeak-ng
        
    - name: Convert and run notebook
      run: |
        # Run the notebook using nbconvert
        jupyter nbconvert --to notebook --execute notebook.ipynb --output executed_notebook.ipynb
        
    - name: Upload executed notebook as artifact
      uses: actions/upload-artifact@v3
      with:
        name: executed-notebook
        path: executed_notebook.ipynb
